name: Build/windows
run-name: Build Avesta On Windows
on: [push]
jobs:
  build-dotnet:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@latest
      - run: dotnet build

        
