name: Build/mac
run-name: Build Avesta On mac
on: [push]
jobs:
  build-dotnet:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3

     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v3.0.3
     - run: dotnet --info
     

        
       