name: CI/CD
run-name: CI/CD
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
      - run: dotnet build
        
